name: Red Modding

menu:
  wiki: https://wiki.redmodding.org
  Projects: /projects
  Members: /members
  About us: /about

socials:
  GitHub: https://github.com/WolvenKit/
  Discord: https://discord.com/invite/Epkq79kd96
  Patreon: https://www.patreon.com/RedModdingTools
