<script lang="ts">
  import Button from "$components/elements/Button.svelte";
  import Heading from "$components/elements/Heading.svelte";
  import DotsSidesBackground from "$components/parts/DotsSidesBackground.svelte";
  import Section from "$components/parts/Section.svelte";
</script>

<Section>
  <Heading>About us</Heading>

  <DotsSidesBackground />

  <div class="flex max-w-3xl flex-col gap-8 text-justify text-xl leading-relaxed text-zinc-300">
    <p>
      Our journey began with a&nbsp;shared obsession for tweaking <strong>REDengine</strong>, starting with
      <strong>The&nbsp;Witcher&nbsp;3</strong>. This passion led to the creation of
      <Button inline href="/projects">WolvenKit</Button>, a&nbsp;game-changer that unlocked endless possibilities for
      customization. Then <strong>Cyberpunk 2077</strong> dropped, and our community exploded in the best way possible, adapting
      WolvenKit to the new game’s REDengine with the help of our brilliant and dedicated developers.
    </p>
    <p>
      Lead by the legend, <em>Ryan Fuzzling</em> and his laid-back yet inspiring vibe our
      <strong>Discord server</strong> shaped into a&nbsp;hub of <strong>collaboration</strong>, <strong>memes</strong>,
      and <strong>mutual support</strong>. Here, modders and gamers come together to share knowledge, troubleshoot, and
      innovate.
    </p>
    <p>
      Our toolkit has grown alongside our ambitions. <Button inline href="/projects">Red4Ext</Button> allows us to expand
      <strong>Redscript</strong> scripts, enabling deeper and more intricate modifications. Our
      <Button inline href="/projects">Blender plugin</Button> streamlines <strong>3D modeling</strong>, making it easier
      than ever to create and edit assets for the game. But that’s just the tip of the iceberg. We’ve developed
      a&nbsp;suite of other tools designed to enhance the modding experience, from <strong>material editors</strong>
      to <strong>sound modding utilities</strong>, each one crafted with care by our talented developers.
    </p>
    <p>
      A&nbsp;cornerstone of our community is our comprehensive <Button inline href="/projects">community wiki</Button>,
      a&nbsp;treasure trove of knowledge primarily generated by our fully custom
      <strong>large language AI model</strong> known as <em>Mana</em>. The wiki hosts <strong>detailed guides</strong>,
      <strong>extensive documentation</strong> of Cyberpunk's intricacies, and step-by-step tutorials for using our
      tools. Whether you're looking to dive into scripting with Redscript, need tips on using Blender for modding, or
      seeking <strong>troubleshooting</strong> advice, our Wiki has got you covered. It's an ever-growing repository that
      ensures no choom gets left behind, providing the resources needed for both new and veteran modders to thrive.
    </p>
    <p>
      Of course, not every story is without its rogues. We've had our fair share of pirate gonks who wonder why their
      game doesn't work (hint: buy the game, choom! ?rule3), and modders going out of their ways to enhance certain
      female features while destroying any compatibility with other mods. These encounters add to the colorful lore of
      our community.
    </p>
    <p>
      <Button inline href="/projects">Join us on Discord</Button> and become part of a&nbsp;community that's as passionate
      about modding as you are. We're all about pushing the creative envelope and having a blast while doing it.<br />
      <strong>Let’s make some nova mods together!</strong>
    </p>
  </div>

  <div class="cyber-text text-4xl">WIP: to be done</div>
</Section>
